import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {

  return (
    <>
      <Head>
        <title>Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/WHlogo.ico" />
      </Head>
      <Navbar/>
      <Contact/>
      <Footer/>
    </>
  )
}
