import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Portfolio from '../components/Portfolio'

export default function Home() {

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/WHlogo.ico" />
      </Head>
      <Navbar/>
      <Portfolio/>

      <Footer/>
    </>
  )
}
