import Head from 'next/head'
import Navbar from '../components/Navbar'
import Project from '../components/Project'
import Footer from '../components/Footer'

export default function Home() {

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/WHlogo.ico" />
      </Head>
      <Navbar/>
      <Project/>
      <Footer/>
    </>
  )
}
